### ISSUE TITLE
Show solcjs compilation flags information

### ISSUE THREAD

**Issue by adria0** [trufflesuite/truffle-compile#10]
There's a tuning about optimization loops in

https://github.com/trufflesuite/truffle-compile/blob/331809c73389f27f9dda40229061bb75b18f27ca/index.js#L70

but, since this modification it's not a default in solcjs, and it is not warned there's no way to verify the code in etherscan once deployed.

I sent a email to etherscan about supporting this compilation flag, too.

**Comment by tcoulter** [comment]
We'll add the default parameters to our documentation. We've created a ticket that will allow people to override the default compiler optimization setting. trufflesuite/truffle#486.

**Comment by tcoulter** [comment]
Thanks!
