### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by dylanseago** [trufflesuite/truffle-compile#11]
Problematic dependencies:
- [truffle-config@0.0.7](https://github.com/trufflesuite/truffle-config/commit/ae1319b2c16ae24eff47c7bbe3da73b3be984dfa) broken due to https://github.com/trufflesuite/truffle-config/issues/2
- [truffle-resolver@2.0.0](https://github.com/trufflesuite/truffle-resolver/commit/444fe31ada31e5c3ecab7dadf808d3224d1aa937) broken due to transitive dependency on [truffle-contract@1.1.x](https://github.com/trufflesuite/truffle-contract/commit/36db246805ef40e4175465c717df1107cefb16c6), see https://github.com/trufflesuite/truffle-contract/issues/31

**Comment by tcoulter** [comment]
Thanks for the issues. Closing this one. We'll go through them all in one pass. Thanks!
