### ISSUE TITLE
Modifying a base contract doesn't trigger recompilation of derived contracts.

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle-compile#47]
(Moved from https://github.com/trufflesuite/truffle/issues/839)
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Modifying a base contract doesn't trigger recompilation of derived contracts.

## Steps to Reproduce

1. Copy `Alpha.sol` and `Beta.sol` from https://github.com/ethereum/solidity/issues/3675 to a new Truffle project's `contracts` directory.
2. In the project directory, `truffle compile`.  
3. To Alpha.sol, add the following before the final closing curly brace: 

        function newFunctionInBaseContract(uint newValue) public {
            secondField = newValue;
        }

4. In the project directory, `truffle compile` again, as many times as you want.  
5. Inspect ABI of `Beta` in `build/contracts/Beta.json`.

## Expected Behavior

The output from `truffle compile` should be:   

> Compiling .\contracts\Alpha.sol...
> Compiling .\contracts\Beta.sol...
> Writing artifacts to .\build\contracts

ABIs in `Alpha.json` and `Beta.json` should both contain `newFunctionInBaseContract`.

## Actual Results

The output from `truffle compile` is:   

> Compiling .\contracts\Alpha.sol...
> Writing artifacts to .\build\contracts

and while `Alpha.json` contains the ABI including `newFunctionInBaseContract`, `Beta` does not.

## Environment

* Operating System: Windows 10
* Ethereum client: N/A 
* Truffle version (`truffle version`): Truffle v4.0.4 (core: 4.0.4)
* solidity version: Solidity v0.4.18 (solc-js)
* node version (`node --version`): v9.3.0
* npm version (`npm --version`): v5.6.0

**Comment by wbt** [comment]
I suspect the issue is in [profiler.js](https://github.com/trufflesuite/truffle-compile/blob/develop/profiler.js) in [`required_sources`](https://github.com/trufflesuite/truffle-compile/blob/6584837caf236922f37ccd9a96680c4baa76882b/profiler.js#L161) or [`dependency_graph`](https://github.com/trufflesuite/truffle-compile/blob/6584837caf236922f37ccd9a96680c4baa76882b/profiler.js#L249).
The updated files are added to the list in line [149](https://github.com/trufflesuite/truffle-compile/blob/6584837caf236922f37ccd9a96680c4baa76882b/profiler.js#L148) based just on file update time.  This is returned to [index.js:299](https://github.com/trufflesuite/truffle-compile/blob/3c4f482e814dc75bb8ac9382417252fd1d1f1331/index.js#L299), then passed as `options.paths` to `compile.with_dependencies` which at line [325](https://github.com/trufflesuite/truffle-compile/blob/3c4f482e814dc75bb8ac9382417252fd1d1f1331/index.js#L325) bounces it back to [Profiler.required_sources](https://github.com/trufflesuite/truffle-compile/blob/6584837caf236922f37ccd9a96680c4baa76882b/profiler.js#L161).  
I don't have time to dive deeper at the moment but hope this helps.

**Comment by gnidan** [comment]
This is a known issue, there's WIP to address this in #41

**Comment by cgewecke** [comment]
This is fixed as of `4.1.5`. Thanks @wbt.
