### ISSUE TITLE
Bump solidity version

### ISSUE THREAD

**Issue by axic** [trufflesuite/truffle-compile#50]
Truffle is currently stuck with 0.4.19, the last release was 0.4.21 and 0.4.22 planned within the next two weeks.

A lot of warnings are introduced for things which are going to be errors in 0.5.0. If these 0.4.x releases are not rolled out in time to the users there will be a bigger shock receiving 0.5.0.

Please update to 0.4.21 😉

**Comment by cgewecke** [comment]
@axic Thanks for the reminder :) 

Will include this in a patch release we've tentatively scheduled for the start of next week (~ 3/26)

**Comment by kyriediculous** [comment]
Truffle is a bunch of shit...
Compiler versions hopelessly behind
ABI gets corrupted on recompiling and your solution is "delete your build folder"

Hilariously unprofessional

**Comment by cgewecke** [comment]
@kyriediculous Fair enough - agree we need to fix both of these issues. They're high priority, apologies.

**Comment by ghost** [comment]
thank you for good support and fast fix, everything work now)))

**Comment by gnidan** [comment]
This has been released in Truffle v4.1.4. Thanks!

**Comment by axic** [comment]
Thank you!

I'll ping you in a week for the next one 🕺

**Comment by gnidan** [comment]
Keep 'em coming :)
