### ISSUE TITLE
allow to choose a solc version and optimization flag

### ISSUE THREAD

**Issue by ajunge** [trufflesuite/truffle-compile#7]
I think there is no way to choose a solc version. This could be set up in the truffle.js file:

```
{
   compiler: {
      version: "0.4.8",
      optimization: false
  }
}
```

**Comment by vyorkin** [comment]
To make this possible we need to somehow get rid of the direct dependency on [solc package](https://github.com/ethereum/solc-js): https://github.com/trufflesuite/truffle-compile/blob/master/package.json#L10 or just use it as a default compiler when it isn't specified by user. Any ideas?
related: https://github.com/trufflesuite/truffle/issues/265

**Comment by IstoraMandiri** [comment]
This should now be possible with the latest version.

Ideally we can override the entire config object:

https://github.com/trufflesuite/truffle-compile/blob/master/index.js#L64-L85

**Comment by tcoulter** [comment]
Because `solc` actively changes their input and output formats regularly, we won't allow users to specify the specific version of the compiler *right now*. For instance, the input and output formats changed twice between versions `0.4.9`, `0.4.10` and `0.4.11`. With their standard input and output formats now, this should stabilize, but for now we're going to put off allowing changes to the compiler version. 

However! We do want to make the compiler setting configurable. We'll be tracking that work in a new ticket. Stay tuned.

**Comment by tcoulter** [comment]
Ah, here's where we're tracking the optimization configuration: #486. 

I'm going to close this ticket for now. We'll consider making the Solidity version upgradable in a future ticket. Cheers! Thanks all.

**Comment by Pipeliner** [comment]
Hi @tcoulter, there does not seem to be an issue #486.
Where can I find more up to date info?

_Update:_ that issue seems to be https://github.com/trufflesuite/truffle/issues/486.

**Comment by Pipeliner** [comment]
@tcoulter it would still be nice to be able to choose solc version.

**Comment by OTTTO** [comment]
@tcoulter yes, it would be nice to not have to go into my lib/node-modules and reinstall solc@x.y.z every time

**Comment by Raz0r** [comment]
+1

**Comment by migueljvaz** [comment]
+1

**Comment by ilanDoron** [comment]
+1

**Comment by Przemek-Win** [comment]
+1

**Comment by celeduc** [comment]
This is now possible in truffle v0.5.x.

in truffle config:
```javascript
module.exports = {
  compilers: {
    solc: {
      version: <string>, // A version or constraint - Ex. "^0.5.0"
                         // Can also be set to "native" to use a native solc
      settings: {
        optimizer: {
          enabled: <boolean>,
          runs: <number>   // Optimize for how many times you intend to run the code
        }
      }
    }
  }
}
```
https://truffleframework.com/docs/truffle/reference/configuration#solc

**Comment by pieterhartel** [comment]
Thanks for this great feature, very useful. However, I was wondering which version of the EVM will be used with a specific compiler version. The reason I am asking is because I am interested in studying history by recreating it. And a historic compiler with a modern EVM is not quite right.
