### ISSUE TITLE
Expose evmVersion as an option

### ISSUE THREAD

**Issue by axic** [trufflesuite/truffle-compile#72]
Recent compiler versions introduced `evmVersion` as a setting in the JSON. If the field is missing, it defaults to `byzantium` which enables the use of `returndatacopy`. This has caused some issues with non-compliant ERC20 token contracts (see https://github.com/ethereum/solidity/issues/4116 for more).

Other options include `homestead`, `spuriousDragon` and `tangerineWhistle`. It would make sense to support this option so that those requiring it could resort to the old, unsafe, behaviour.

**Comment by axic** [comment]
@cgewecke @gnidan I think this is now supported based on the two merged PRs?

**Comment by cgewecke** [comment]
@axic Apologies, missed this. It looks like we'll be releasing on Monday. 

As a side-note -  we moved all the truffle modules into a monorepo at [trufflesuite/truffle](https://github.com/trufflesuite/truffle) this week. This repo is going to be archived and all the issues will be tracked in one place over there ;)

**Comment by axic** [comment]
Did this make it into one of the releases yet in the 4.x series? 😉

**Comment by gnidan** [comment]
@axic yep, looks like this went out with v4.1.12!

**Comment by axic** [comment]
Great thanks!

**Comment by axic** [comment]
@gnidan sorry to ask in this place, but how can this be used in the configuration?

**Comment by gnidan** [comment]
> sorry to ask in this place, but how can this be used in the configuration?

At `compilers.solc.settings.evmVersion`. See docs [here](https://truffleframework.com/docs/truffle/reference/configuration#solc)

**Comment by axic** [comment]
Thank you, that's great!
